apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=820171506892.dkr.ecr.us-east-1.amazonaws.com/backend,
      frontend=820171506892.dkr.ecr.us-east-1.amazonaws.com/frontend

    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest

    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^v.*
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^v.*

    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helm
spec:
  project: default
  source:
    repoURL: https://github.com/Nehabisen21/Final-Devops-Project.git
    targetRevision: master
    path: Kubernetes/Helm/fullstack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: projectns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
