    backend:
  image:
    repository: 820171506892.dkr.ecr.us-east-1.amazonaws.com/backend
    tag: v1
  replicaCount: 1

frontend:
  image:
    repository: 820171506892.dkr.ecr.us-east-1.amazonaws.com/frontend
    tag: v1
  replicaCount: 1

phoenix:
  image:
    repository: arizephoenix/phoenix
    tag: latest
  replicaCount: 1
